name: jihe2
on:
  schedule:
    - cron: '1 1,16 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: jihe2
jobs:
  repo-sync:
    env:
      AC: ${{ secrets.AC }}
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: sync curtinlv
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/curtinlv/JD-Script.git"
          source_branch: "main"
          destination_branch: "curtinlv-JD"
          github_token: ${{ secrets.AC }} 
          
      - name: sync hundun
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/whyour/hundun.git"
          source_branch: "master"
          destination_branch: "hundun"   
          github_token: ${{ secrets.AC }}
          
          
      - name: sync ssh
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/FunctionClub/Fail2ban.git"
          source_branch: "master"
          destination_branch: "fail2ban"
          github_token: ${{ secrets.AC }}
          
      - name: sync WeHalo
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/aquanlerou/WeHalo.git"
          source_branch: "main"
          destination_branch: "WeHalo"   
          github_token: ${{ secrets.AC }}
          
      - name: sync js_tool
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/lan-tianxiang/js_tool.git"
          source_branch: "A1"
          destination_branch: "js_tool"   
          github_token: ${{ secrets.AC }}
          
      - name: sync V3
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/lan-tianxiang/jd_shell.git"
          source_branch: "v3"
          destination_branch: "V3"   
          github_token: ${{ secrets.AC }}
          
      - name: sync Hydrahail-Johnson
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/Hydrahail-Johnson/scripts.git"
          source_branch: "main"
          destination_branch: "Hydrahail-Johnson"   
          github_token: ${{ secrets.AC }}
                    
      - name: sync jd
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/jiulan/jd_v4.git"
          source_branch: "main"
          destination_branch: "jdv4"   
          github_token: ${{ secrets.AC }}
          
      # 我自己同步到gitee使用，其他人可忽略
      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key
        with:
          src: github/NM1688
          dst: gitee/NM1688
          static_list: "JDDJ"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
