name: sync
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync
jobs:
  repo-sync:
    env:
      AC: ${{ secrets.AC }}
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync JDDJ
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/passerby-b/JDDJ.git"
          source_branch: "main"
          destination_branch: "master"
          github_token: ${{ secrets.AC }}
          
      - name: sync free
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/freefq/free.git"
          source_branch: "master"
          destination_branch: "freefq-free"
          github_token: ${{ secrets.AC }}
          
      - name: sync JDMemberCloseAccount
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/yqchilde/JDMemberCloseAccount.git"
          source_branch: "main"
          destination_branch: "yqchilde-JDMemberCloseAccount"
          github_token: ${{ secrets.AC }}
          
      - name: sync daily_scripts
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/ZCY01/daily_scripts.git"
          source_branch: "main"
          destination_branch: "ZCY01-daily_scripts"
          github_token: ${{ secrets.AC }}




      - name: sync jd_scripts
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/chinnkarahoi/jd_scripts.git"
          source_branch: "master"
          destination_branch: "jd_scripts"
          github_token: ${{ secrets.AC }}
          
          
          
          
      - name: sync jd-scripts-docker
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/chinnkarahoi/jd-scripts-docker.git"
          source_branch: "master"
          destination_branch: "docker"
          github_token: ${{ secrets.AC }}
          
          
      - name: sync jd-scripts
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/JDHelloWorld/jd_scripts.git"
          source_branch: "main"
          destination_branch: "JDHelloWorld-jd_scripts"
          github_token: ${{ secrets.AC }}
          
      - name: sync jd
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/star261/jd.git"
          source_branch: "main"
          destination_branch: "star261-jd"
          github_token: ${{ secrets.AC }}
          
      - name: sync buqian
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/buqian123/faker3"
          source_branch: "main"
          destination_branch: "buqian"
          github_token: ${{ secrets.AC }}
          
      - name: sync qinglong
        uses: repo-sync/github-sync@v2
        if: env.AC
        with:
          source_repo: "https://github.com/whyour/qinglong.git"
          source_branch: "master"
          destination_branch: "qinglong"
          github_token: ${{ secrets.AC }}
          
   
      # 我自己同步到gitee使用，其他人可忽略
      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key
        with:
          src: github/NM1688
          dst: gitee/NM1688
          static_list: "JDDJ"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
