name: sync
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync JDDJ
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/passerby-b/JDDJ.git"
          source_branch: "main"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
      - name: sync free
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/freefq/free.git"
          source_branch: "master"
          destination_branch: "freefq-free"
          github_token: ${{ secrets.PAT }}
      - name: sync JDMemberCloseAccount
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/yqchilde/JDMemberCloseAccount.git"
          source_branch: "main"
          destination_branch: "yqchilde-JDMemberCloseAccount"
          github_token: ${{ secrets.PAT }}
      - name: sync daily_scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ZCY01/daily_scripts.git"
          source_branch: "main"
          destination_branch: "ZCY01-daily_scripts"
          github_token: ${{ secrets.PAT }}
      - name: sync longzhuzhu
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/longzhuzhu/nianyu.git"
          source_branch: "main"
          destination_branch: "longzhuzhu-nianyu"
          github_token: ${{ secrets.PAT }}
      - name: sync jd_scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/chinnkarahoi/jd_scripts.git"
          source_branch: "master"
          destination_branch: "jd_scripts"
          github_token: ${{ secrets.PAT }}
      - name: sync jd-scripts-docker
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/chinnkarahoi/jd-scripts-docker.git"
          source_branch: "master"
          destination_branch: "docker"
          github_token: ${{ secrets.PAT }}
      - name: sync jd-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/JDHelloWorld/jd_scripts.git"
          source_branch: "main"
          destination_branch: "JDHelloWorld-jd_scripts"
          github_token: ${{ secrets.PAT }}
      - name: sync jd
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/star261/jd.git"
          source_branch: "main"
          destination_branch: "star261-jd"
          github_token: ${{ secrets.PAT }}
      - name: sync ZOO
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/zooPanda/zoo.git"
          source_branch: "dev"
          destination_branch: "zooPanda-zoo"
          github_token: ${{ secrets.PAT }}
      - name: sync qinglong
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/whyour/qinglong.git"
          source_branch: "master"
          destination_branch: "qinglong"
          github_token: ${{ secrets.PAT }}
      - name: sync JDBrandMember
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/AntonVanke/JDBrandMember.git"
          source_branch: "main"
          destination_branch: "AntonVanke-JDBrandMember"
          github_token: ${{ secrets.PAT }}
      - name: sync dailycheckin
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Sitoi/dailycheckin.git"
          source_branch: "main"
          destination_branch: "Sitoi-dailycheckin"
          github_token: ${{ secrets.PAT }}
      - name: sync jd-base
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lxrcbw/jd-base_dockere.git"
          source_branch: "master"
          destination_branch: "jd-base"
          github_token: ${{ secrets.PAT }}
      - name: sync js_script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/qq34347476/js_script.git"
          source_branch: "master"
          destination_branch: "js_script"
          github_token: ${{ secrets.PAT }} 
      - name: sync jiandjh-docker
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://gitee.com/jiandjh/docker.git"
          source_branch: "main"
          destination_branch: "jiandjh-docker"
          github_token: ${{ secrets.PAT }}
      - name: sync dust
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Wpenga/dust.git"
          source_branch: "main"
          destination_branch: "heshang-dust"
          github_token: ${{ secrets.PAT }}
      - name: sync dd
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/piaoyun/dd.git"
          source_branch: "main"
          destination_branch: "v4panel"
          github_token: ${{ secrets.PAT }}
      - name: sync NobyDa
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/NobyDa/Script.git"
          source_branch: "master"
          destination_branch: "NobyDa"
          github_token: ${{ secrets.PAT }}
      - name: sync yangtingxiao
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/yangtingxiao/QuantumultX.git"
          source_branch: "master"
          destination_branch: "yangtingxiao-QuantumultX"
          github_token: ${{ secrets.PAT }}
      - name: sync wuzhi
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/wuzhi04/MyActions.git"
          source_branch: "main"
          destination_branch: "wuzhi"
          github_token: ${{ secrets.PAT }}
      - name: sync elecV2P
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/elecV2/elecV2P.git"
          source_branch: "master"
          destination_branch: "elecV2P"
          github_token: ${{ secrets.PAT }}
      - name: sync curtinlv
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/curtinlv/JD-Script.git"
          source_branch: "main"
          destination_branch: "curtinlv-JD"
          github_token: ${{ secrets.PAT }}  
      - name: sync hundun
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/whyour/hundun.git"
          source_branch: "master"
          destination_branch: "hundun"   
          github_token: ${{ secrets.PAT }}
      - name: sync JDC
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/cdlaimin/JDC.git"
          source_branch: "master"
          destination_branch: "JDC"   
          github_token: ${{ secrets.PAT }}
      - name: sync ssh
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/FunctionClub/Fail2ban.git"
          source_branch: "master"
          destination_branch: "fail2ban"
          github_token: ${{ secrets.PAT }}
      - name: sync WeHalo
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/aquanlerou/WeHalo.git"
          source_branch: "main"
          destination_branch: "WeHalo"   
          github_token: ${{ secrets.PAT }}
      - name: sync js_tool
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lan-tianxiang/js_tool.git"
          source_branch: "A1"
          destination_branch: "js_tool"   
          github_token: ${{ secrets.PAT }}
      - name: sync V3
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lan-tianxiang/jd_shell.git"
          source_branch: "v3"
          destination_branch: "V3"   
          github_token: ${{ secrets.PAT }}
      - name: sync Hydrahail-Johnson
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Hydrahail-Johnson/scripts.git"
          source_branch: "main"
          destination_branch: "Hydrahail-Johnson"   
          github_token: ${{ secrets.PAT }}     
      # 我自己同步到gitee使用，其他人可忽略
      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key
        with:
          src: github/NM1688
          dst: gitee/NM1688
          static_list: "JDDJ"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
